export enum ALDataTypes {
    none = "none", array = "array", Action = "Action",
    BigInteger = "BigInteger", BigText = "BigText", Boolean = "Boolean", Byte = "Byte",
    Char = "Char", ClientType = "ClientType", Code = "Code", Codeunit = "Codeunit", ControlAddIn = "ControlAddIn",
    DataClassification = "DataClassification", DataScope = "DataScope", Date = "Date", DateFormula = "DateFormula", DateTime = "DateTime", Decimal = "Decimal", DefaultLayout = "DefaultLayout", Dialog = "Dialog", Dictionary = "Dictionary", DotNet = "DotNet", Duration = "Duration",
    Enum = "Enum", ErrorInfo = "ErrorInfo", ErrorType = "ErrorType", ExecutionContext = "ExecutionContext", ExecutionMode = "ExecutionMode",
    FieldClass = "FieldClass", FieldRef = "FieldRef", FieldType = "FieldType", File = "File", FilterPageBuilder = "FilterPageBuilder",
    Guid = "Guid",
    HttpClient = "HttpClient", HttpContent = "HttpContent", HttpHeaders = "HttpHeaders", HttpRequestMessage = "HttpRequestMessage", HttpResponseMessage = "HttpResponseMessage",
    InStream = "InStream", Integer = "Integer",
    Interface = "Interface",
    JsonArray = "JsonArray", JsonObject = "JsonObject", JsonToken = "JsonToken", JsonValue = "JsonValue",
    KeyRef = "KeyRef",
    Label = "Label", List = "List",
    ModuleDependencyInfo = "ModuleDependencyInfo", ModuleInfo = "ModuleInfo",
    Notification = "Notification", NotificationScope = "NotificationScope",
    ObjectType = "ObjectType", Option = "Option", OutStream = "OutStream",
    Page = "Page", PageBackgroundTaskErrorLevel = "PageBackgroundTaskErrorLevel",
    Query = "Query",
    Record = "Record", RecordId = "RecordId", RecordRef = "RecordRef", Report = "Report", ReportFormat = "ReportFormat",
    SecurityFilter = "SecurityFilter", SessionSettings = "SessionSettings",
    TableConnectionType = "TableConnectionType", TestPage = "TestPage", TestPermissions = "TestPermissions", Text = "Text", TextBuilder = "TextBuilder", TextConst = "TextConst", TextEncoding = "TextEncoding", Time = "Time", TransactionModel = "TransactionModel", TransactionType = "TransactionType",
    Variant = "Variant", Verbosity = "Verbosity", Version = "Version",
    WebServiceActionConText = "WebServiceActionConText", WebServiceActionResultCode = "WebServiceActionResultCode",
    XmlAttribute = "XmlAttribute", XmlAttributeCollection = "XmlAttributeCollection", XmlCData = "XmlCData", XmlComment = "XmlComment", XmlDeclaration = "XmlDeclaration", XmlDocument = "XmlDocument", XmlDocumentType = "XmlDocumentType", XmlElement = "XmlElement", XmlNamespaceManager = "XmlNamespaceManager", XmlNameTable = "XmlNameTable", XmlNode = "XmlNode", XmlNodeList = "XmlNodeList", XmlPort = "XmlPort", XmlProcessingInstruction = "XmlPort", XmlReadOptions = "XmlReadOptions", XmlText = "XmlText", XmlWriteOptions = "XmlWriteOptions"
}

